// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class MessageBuf;
@class MessageBufBuilder;
@class MessageBufEventMessage;
@class MessageBufEventMessageBuilder;
@class MessageBufKeepAlive;
@class MessageBufKeepAliveBuilder;
@class MessageBufKeepAliveReceipt;
@class MessageBufKeepAliveReceiptBuilder;
@class MessageBufLoginACK;
@class MessageBufLoginACKBuilder;
@class MessageBufMessage;
@class MessageBufMessageACK;
@class MessageBufMessageACKBuilder;
@class MessageBufMessageBuilder;
@class MessageBufNotice;
@class MessageBufNoticeBuilder;
@class MessageBufReceipt;
@class MessageBufReceiptBuilder;
@class MessageBufSession;
@class MessageBufSessionBuilder;
@class MessageBufUser;
@class MessageBufUserBuilder;


typedef NS_ENUM(SInt32, MessageBufRequestTypeEnum) {
  MessageBufRequestTypeEnumSingleMsg = 0,
  MessageBufRequestTypeEnumGroupMsg = 1,
  MessageBufRequestTypeEnumPushMsg = 2,
  MessageBufRequestTypeEnumEventMsg = 3,
  MessageBufRequestTypeEnumSession = 4,
  MessageBufRequestTypeEnumLogin = 100,
  MessageBufRequestTypeEnumLogout = 101,
  MessageBufRequestTypeEnumKeepalive = 102,
  MessageBufRequestTypeEnumReceipt = 103,
  MessageBufRequestTypeEnumNotice = 104,
};

BOOL MessageBufRequestTypeEnumIsValidValue(MessageBufRequestTypeEnum value);
NSString *NSStringFromMessageBufRequestTypeEnum(MessageBufRequestTypeEnum value);

typedef NS_ENUM(SInt32, MessageBufMessageTypeEnum) {
  MessageBufMessageTypeEnumText = 1,
  MessageBufMessageTypeEnumPhoto = 2,
  MessageBufMessageTypeEnumVoice = 3,
  MessageBufMessageTypeEnumUpdateNum = 4,
  MessageBufMessageTypeEnumUpdateStatus = 5,
  MessageBufMessageTypeEnumDelete = 6,
};

BOOL MessageBufMessageTypeEnumIsValidValue(MessageBufMessageTypeEnum value);
NSString *NSStringFromMessageBufMessageTypeEnum(MessageBufMessageTypeEnum value);

typedef NS_ENUM(SInt32, MessageBufNoticeTypeEnum) {
  MessageBufNoticeTypeEnumKickUser = 1,
  MessageBufNoticeTypeEnumSystem = 2,
};

BOOL MessageBufNoticeTypeEnumIsValidValue(MessageBufNoticeTypeEnum value);
NSString *NSStringFromMessageBufNoticeTypeEnum(MessageBufNoticeTypeEnum value);

typedef NS_ENUM(SInt32, MessageBufLoginTypeEnum) {
  MessageBufLoginTypeEnumManualLogin = 1,
  MessageBufLoginTypeEnumAutoLogin = 2,
};

BOOL MessageBufLoginTypeEnumIsValidValue(MessageBufLoginTypeEnum value);
NSString *NSStringFromMessageBufLoginTypeEnum(MessageBufLoginTypeEnum value);

typedef NS_ENUM(SInt32, MessageBufDeviceTypeEnum) {
  MessageBufDeviceTypeEnumPc = 1,
  MessageBufDeviceTypeEnumWeb = 2,
  MessageBufDeviceTypeEnumAndroid = 3,
  MessageBufDeviceTypeEnumIos = 4,
  MessageBufDeviceTypeEnumIpad = 5,
  MessageBufDeviceTypeEnumWinphone = 6,
};

BOOL MessageBufDeviceTypeEnumIsValidValue(MessageBufDeviceTypeEnum value);
NSString *NSStringFromMessageBufDeviceTypeEnum(MessageBufDeviceTypeEnum value);

typedef NS_ENUM(SInt32, MessageBufACKTypeEnum) {
  MessageBufACKTypeEnumConnectAck = 1,
  MessageBufACKTypeEnumLoginAck = 2,
  MessageBufACKTypeEnumMessageAck = 3,
  MessageBufACKTypeEnumLogoutAck = 4,
  MessageBufACKTypeEnumSendMsgAck = 5,
  MessageBufACKTypeEnumMsgInceptAck = 6,
};

BOOL MessageBufACKTypeEnumIsValidValue(MessageBufACKTypeEnum value);
NSString *NSStringFromMessageBufACKTypeEnum(MessageBufACKTypeEnum value);

typedef NS_ENUM(SInt32, MessageBufACKCodeEnum) {
  MessageBufACKCodeEnumSuccess = 0,
  MessageBufACKCodeEnumFailure = 1,
};

BOOL MessageBufACKCodeEnumIsValidValue(MessageBufACKCodeEnum value);
NSString *NSStringFromMessageBufACKCodeEnum(MessageBufACKCodeEnum value);


@interface MessageRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define MessageBuf_isRequest @"isRequest"
#define MessageBuf_requestType @"requestType"
#define MessageBuf_message @"message"
#define MessageBuf_session @"session"
#define MessageBuf_notice @"notice"
#define MessageBuf_keepAlive @"keepAlive"
#define MessageBuf_user @"user"
#define MessageBuf_receipt @"receipt"
#define MessageBuf_keepAliveReceipt @"keepAliveReceipt"
@interface MessageBuf : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasIsRequest_:1;
  BOOL hasMessage_:1;
  BOOL hasSession_:1;
  BOOL hasNotice_:1;
  BOOL hasKeepAlive_:1;
  BOOL hasUser_:1;
  BOOL hasReceipt_:1;
  BOOL hasKeepAliveReceipt_:1;
  BOOL hasRequestType_:1;
  BOOL isRequest_:1;
  MessageBufMessage* message;
  MessageBufSession* session;
  MessageBufNotice* notice;
  MessageBufKeepAlive* keepAlive;
  MessageBufUser* user;
  MessageBufReceipt* receipt;
  MessageBufKeepAliveReceipt* keepAliveReceipt;
  MessageBufRequestTypeEnum requestType;
}
- (BOOL) hasIsRequest;
- (BOOL) hasRequestType;
- (BOOL) hasMessage;
- (BOOL) hasSession;
- (BOOL) hasNotice;
- (BOOL) hasKeepAlive;
- (BOOL) hasUser;
- (BOOL) hasReceipt;
- (BOOL) hasKeepAliveReceipt;
- (BOOL) isRequest;
@property (readonly) MessageBufRequestTypeEnum requestType;
@property (readonly, strong) MessageBufMessage* message;
@property (readonly, strong) MessageBufSession* session;
@property (readonly, strong) MessageBufNotice* notice;
@property (readonly, strong) MessageBufKeepAlive* keepAlive;
@property (readonly, strong) MessageBufUser* user;
@property (readonly, strong) MessageBufReceipt* receipt;
@property (readonly, strong) MessageBufKeepAliveReceipt* keepAliveReceipt;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageBufBuilder*) builder;
+ (MessageBufBuilder*) builder;
+ (MessageBufBuilder*) builderWithPrototype:(MessageBuf*) prototype;
- (MessageBufBuilder*) toBuilder;

+ (MessageBuf*) parseFromData:(NSData*) data;
+ (MessageBuf*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBuf*) parseFromInputStream:(NSInputStream*) input;
+ (MessageBuf*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBuf*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageBuf*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define Session_to @"to"
#define Session_title @"title"
#define Session_sessId @"sessId"
#define Session_msgId @"msgId"
#define Session_msgVer @"msgVer"
#define Session_sessVer @"sessVer"
#define Session_readVer @"readVer"
#define Session_unReadNum @"unReadNum"
@interface MessageBufSession : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTo_:1;
  BOOL hasSessId_:1;
  BOOL hasMsgId_:1;
  BOOL hasMsgVer_:1;
  BOOL hasSessVer_:1;
  BOOL hasReadVer_:1;
  BOOL hasUnReadNum_:1;
  BOOL hasTitle_:1;
  SInt64 to;
  SInt64 sessId;
  SInt64 msgId;
  SInt64 msgVer;
  SInt64 sessVer;
  SInt64 readVer;
  SInt32 unReadNum;
  NSString* title;
}
- (BOOL) hasTo;
- (BOOL) hasTitle;
- (BOOL) hasSessId;
- (BOOL) hasMsgId;
- (BOOL) hasMsgVer;
- (BOOL) hasSessVer;
- (BOOL) hasReadVer;
- (BOOL) hasUnReadNum;
@property (readonly) SInt64 to;
@property (readonly, strong) NSString* title;
@property (readonly) SInt64 sessId;
@property (readonly) SInt64 msgId;
@property (readonly) SInt64 msgVer;
@property (readonly) SInt64 sessVer;
@property (readonly) SInt64 readVer;
@property (readonly) SInt32 unReadNum;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageBufSessionBuilder*) builder;
+ (MessageBufSessionBuilder*) builder;
+ (MessageBufSessionBuilder*) builderWithPrototype:(MessageBufSession*) prototype;
- (MessageBufSessionBuilder*) toBuilder;

+ (MessageBufSession*) parseFromData:(NSData*) data;
+ (MessageBufSession*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufSession*) parseFromInputStream:(NSInputStream*) input;
+ (MessageBufSession*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufSession*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageBufSession*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageBufSessionBuilder : PBGeneratedMessageBuilder {
@private
  MessageBufSession* resultSession;
}

- (MessageBufSession*) defaultInstance;

- (MessageBufSessionBuilder*) clear;
- (MessageBufSessionBuilder*) clone;

- (MessageBufSession*) build;
- (MessageBufSession*) buildPartial;

- (MessageBufSessionBuilder*) mergeFrom:(MessageBufSession*) other;
- (MessageBufSessionBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageBufSessionBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTo;
- (SInt64) to;
- (MessageBufSessionBuilder*) setTo:(SInt64) value;
- (MessageBufSessionBuilder*) clearTo;

- (BOOL) hasTitle;
- (NSString*) title;
- (MessageBufSessionBuilder*) setTitle:(NSString*) value;
- (MessageBufSessionBuilder*) clearTitle;

- (BOOL) hasSessId;
- (SInt64) sessId;
- (MessageBufSessionBuilder*) setSessId:(SInt64) value;
- (MessageBufSessionBuilder*) clearSessId;

- (BOOL) hasMsgId;
- (SInt64) msgId;
- (MessageBufSessionBuilder*) setMsgId:(SInt64) value;
- (MessageBufSessionBuilder*) clearMsgId;

- (BOOL) hasMsgVer;
- (SInt64) msgVer;
- (MessageBufSessionBuilder*) setMsgVer:(SInt64) value;
- (MessageBufSessionBuilder*) clearMsgVer;

- (BOOL) hasSessVer;
- (SInt64) sessVer;
- (MessageBufSessionBuilder*) setSessVer:(SInt64) value;
- (MessageBufSessionBuilder*) clearSessVer;

- (BOOL) hasReadVer;
- (SInt64) readVer;
- (MessageBufSessionBuilder*) setReadVer:(SInt64) value;
- (MessageBufSessionBuilder*) clearReadVer;

- (BOOL) hasUnReadNum;
- (SInt32) unReadNum;
- (MessageBufSessionBuilder*) setUnReadNum:(SInt32) value;
- (MessageBufSessionBuilder*) clearUnReadNum;
@end

#define Message_msgId @"msgId"
#define Message_appId @"appId"
#define Message_type @"type"
#define Message_subType @"subType"
#define Message_from @"from"
#define Message_fromNickName @"fromNickName"
#define Message_to @"to"
#define Message_title @"title"
#define Message_summary @"summary"
#define Message_body @"body"
#define Message_clientTime @"clientTime"
#define Message_serverTime @"serverTime"
#define Message_extend1 @"extend1"
@interface MessageBufMessage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasMsgId_:1;
  BOOL hasFrom_:1;
  BOOL hasTo_:1;
  BOOL hasClientTime_:1;
  BOOL hasServerTime_:1;
  BOOL hasType_:1;
  BOOL hasSubType_:1;
  BOOL hasAppId_:1;
  BOOL hasFromNickName_:1;
  BOOL hasTitle_:1;
  BOOL hasSummary_:1;
  BOOL hasBody_:1;
  BOOL hasExtend1_:1;
  SInt64 msgId;
  SInt64 from;
  SInt64 to;
  SInt64 clientTime;
  SInt64 serverTime;
  SInt32 type;
  SInt32 subType;
  NSString* appId;
  NSString* fromNickName;
  NSString* title;
  NSString* summary;
  NSString* body;
  NSString* extend1;
}
- (BOOL) hasMsgId;
- (BOOL) hasAppId;
- (BOOL) hasType;
- (BOOL) hasSubType;
- (BOOL) hasFrom;
- (BOOL) hasFromNickName;
- (BOOL) hasTo;
- (BOOL) hasTitle;
- (BOOL) hasSummary;
- (BOOL) hasBody;
- (BOOL) hasClientTime;
- (BOOL) hasServerTime;
- (BOOL) hasExtend1;
@property (readonly) SInt64 msgId;
@property (readonly, strong) NSString* appId;
@property (readonly) SInt32 type;
@property (readonly) SInt32 subType;
@property (readonly) SInt64 from;
@property (readonly, strong) NSString* fromNickName;
@property (readonly) SInt64 to;
@property (readonly, strong) NSString* title;
@property (readonly, strong) NSString* summary;
@property (readonly, strong) NSString* body;
@property (readonly) SInt64 clientTime;
@property (readonly) SInt64 serverTime;
@property (readonly, strong) NSString* extend1;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageBufMessageBuilder*) builder;
+ (MessageBufMessageBuilder*) builder;
+ (MessageBufMessageBuilder*) builderWithPrototype:(MessageBufMessage*) prototype;
- (MessageBufMessageBuilder*) toBuilder;

+ (MessageBufMessage*) parseFromData:(NSData*) data;
+ (MessageBufMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufMessage*) parseFromInputStream:(NSInputStream*) input;
+ (MessageBufMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageBufMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageBufMessageBuilder : PBGeneratedMessageBuilder {
@private
  MessageBufMessage* resultMessage;
}

- (MessageBufMessage*) defaultInstance;

- (MessageBufMessageBuilder*) clear;
- (MessageBufMessageBuilder*) clone;

- (MessageBufMessage*) build;
- (MessageBufMessage*) buildPartial;

- (MessageBufMessageBuilder*) mergeFrom:(MessageBufMessage*) other;
- (MessageBufMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageBufMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMsgId;
- (SInt64) msgId;
- (MessageBufMessageBuilder*) setMsgId:(SInt64) value;
- (MessageBufMessageBuilder*) clearMsgId;

- (BOOL) hasAppId;
- (NSString*) appId;
- (MessageBufMessageBuilder*) setAppId:(NSString*) value;
- (MessageBufMessageBuilder*) clearAppId;

- (BOOL) hasType;
- (SInt32) type;
- (MessageBufMessageBuilder*) setType:(SInt32) value;
- (MessageBufMessageBuilder*) clearType;

- (BOOL) hasSubType;
- (SInt32) subType;
- (MessageBufMessageBuilder*) setSubType:(SInt32) value;
- (MessageBufMessageBuilder*) clearSubType;

- (BOOL) hasFrom;
- (SInt64) from;
- (MessageBufMessageBuilder*) setFrom:(SInt64) value;
- (MessageBufMessageBuilder*) clearFrom;

- (BOOL) hasFromNickName;
- (NSString*) fromNickName;
- (MessageBufMessageBuilder*) setFromNickName:(NSString*) value;
- (MessageBufMessageBuilder*) clearFromNickName;

- (BOOL) hasTo;
- (SInt64) to;
- (MessageBufMessageBuilder*) setTo:(SInt64) value;
- (MessageBufMessageBuilder*) clearTo;

- (BOOL) hasTitle;
- (NSString*) title;
- (MessageBufMessageBuilder*) setTitle:(NSString*) value;
- (MessageBufMessageBuilder*) clearTitle;

- (BOOL) hasSummary;
- (NSString*) summary;
- (MessageBufMessageBuilder*) setSummary:(NSString*) value;
- (MessageBufMessageBuilder*) clearSummary;

- (BOOL) hasBody;
- (NSString*) body;
- (MessageBufMessageBuilder*) setBody:(NSString*) value;
- (MessageBufMessageBuilder*) clearBody;

- (BOOL) hasClientTime;
- (SInt64) clientTime;
- (MessageBufMessageBuilder*) setClientTime:(SInt64) value;
- (MessageBufMessageBuilder*) clearClientTime;

- (BOOL) hasServerTime;
- (SInt64) serverTime;
- (MessageBufMessageBuilder*) setServerTime:(SInt64) value;
- (MessageBufMessageBuilder*) clearServerTime;

- (BOOL) hasExtend1;
- (NSString*) extend1;
- (MessageBufMessageBuilder*) setExtend1:(NSString*) value;
- (MessageBufMessageBuilder*) clearExtend1;
@end

#define EventMessage_msgId @"msgId"
#define EventMessage_property @"property"
#define EventMessage_type @"type"
#define EventMessage_from @"from"
#define EventMessage_fromNickName @"fromNickName"
#define EventMessage_content @"content"
@interface MessageBufEventMessage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasMsgId_:1;
  BOOL hasFrom_:1;
  BOOL hasProperty_:1;
  BOOL hasType_:1;
  BOOL hasFromNickName_:1;
  BOOL hasContent_:1;
  SInt64 msgId;
  SInt64 from;
  SInt32 property;
  SInt32 type;
  NSString* fromNickName;
  NSString* content;
}
- (BOOL) hasMsgId;
- (BOOL) hasProperty;
- (BOOL) hasType;
- (BOOL) hasFrom;
- (BOOL) hasFromNickName;
- (BOOL) hasContent;
@property (readonly) SInt64 msgId;
@property (readonly) SInt32 property;
@property (readonly) SInt32 type;
@property (readonly) SInt64 from;
@property (readonly, strong) NSString* fromNickName;
@property (readonly, strong) NSString* content;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageBufEventMessageBuilder*) builder;
+ (MessageBufEventMessageBuilder*) builder;
+ (MessageBufEventMessageBuilder*) builderWithPrototype:(MessageBufEventMessage*) prototype;
- (MessageBufEventMessageBuilder*) toBuilder;

+ (MessageBufEventMessage*) parseFromData:(NSData*) data;
+ (MessageBufEventMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufEventMessage*) parseFromInputStream:(NSInputStream*) input;
+ (MessageBufEventMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufEventMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageBufEventMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageBufEventMessageBuilder : PBGeneratedMessageBuilder {
@private
  MessageBufEventMessage* resultEventMessage;
}

- (MessageBufEventMessage*) defaultInstance;

- (MessageBufEventMessageBuilder*) clear;
- (MessageBufEventMessageBuilder*) clone;

- (MessageBufEventMessage*) build;
- (MessageBufEventMessage*) buildPartial;

- (MessageBufEventMessageBuilder*) mergeFrom:(MessageBufEventMessage*) other;
- (MessageBufEventMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageBufEventMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMsgId;
- (SInt64) msgId;
- (MessageBufEventMessageBuilder*) setMsgId:(SInt64) value;
- (MessageBufEventMessageBuilder*) clearMsgId;

- (BOOL) hasProperty;
- (SInt32) property;
- (MessageBufEventMessageBuilder*) setProperty:(SInt32) value;
- (MessageBufEventMessageBuilder*) clearProperty;

- (BOOL) hasType;
- (SInt32) type;
- (MessageBufEventMessageBuilder*) setType:(SInt32) value;
- (MessageBufEventMessageBuilder*) clearType;

- (BOOL) hasFrom;
- (SInt64) from;
- (MessageBufEventMessageBuilder*) setFrom:(SInt64) value;
- (MessageBufEventMessageBuilder*) clearFrom;

- (BOOL) hasFromNickName;
- (NSString*) fromNickName;
- (MessageBufEventMessageBuilder*) setFromNickName:(NSString*) value;
- (MessageBufEventMessageBuilder*) clearFromNickName;

- (BOOL) hasContent;
- (NSString*) content;
- (MessageBufEventMessageBuilder*) setContent:(NSString*) value;
- (MessageBufEventMessageBuilder*) clearContent;
@end

#define Notice_type @"type"
#define Notice_to @"to"
#define Notice_deviceId @"deviceId"
#define Notice_content @"content"
#define Notice_serverTime @"serverTime"
@interface MessageBufNotice : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTo_:1;
  BOOL hasServerTime_:1;
  BOOL hasType_:1;
  BOOL hasDeviceId_:1;
  BOOL hasContent_:1;
  SInt64 to;
  SInt64 serverTime;
  SInt32 type;
  NSString* deviceId;
  NSString* content;
}
- (BOOL) hasType;
- (BOOL) hasTo;
- (BOOL) hasDeviceId;
- (BOOL) hasContent;
- (BOOL) hasServerTime;
@property (readonly) SInt32 type;
@property (readonly) SInt64 to;
@property (readonly, strong) NSString* deviceId;
@property (readonly, strong) NSString* content;
@property (readonly) SInt64 serverTime;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageBufNoticeBuilder*) builder;
+ (MessageBufNoticeBuilder*) builder;
+ (MessageBufNoticeBuilder*) builderWithPrototype:(MessageBufNotice*) prototype;
- (MessageBufNoticeBuilder*) toBuilder;

+ (MessageBufNotice*) parseFromData:(NSData*) data;
+ (MessageBufNotice*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufNotice*) parseFromInputStream:(NSInputStream*) input;
+ (MessageBufNotice*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufNotice*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageBufNotice*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageBufNoticeBuilder : PBGeneratedMessageBuilder {
@private
  MessageBufNotice* resultNotice;
}

- (MessageBufNotice*) defaultInstance;

- (MessageBufNoticeBuilder*) clear;
- (MessageBufNoticeBuilder*) clone;

- (MessageBufNotice*) build;
- (MessageBufNotice*) buildPartial;

- (MessageBufNoticeBuilder*) mergeFrom:(MessageBufNotice*) other;
- (MessageBufNoticeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageBufNoticeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (SInt32) type;
- (MessageBufNoticeBuilder*) setType:(SInt32) value;
- (MessageBufNoticeBuilder*) clearType;

- (BOOL) hasTo;
- (SInt64) to;
- (MessageBufNoticeBuilder*) setTo:(SInt64) value;
- (MessageBufNoticeBuilder*) clearTo;

- (BOOL) hasDeviceId;
- (NSString*) deviceId;
- (MessageBufNoticeBuilder*) setDeviceId:(NSString*) value;
- (MessageBufNoticeBuilder*) clearDeviceId;

- (BOOL) hasContent;
- (NSString*) content;
- (MessageBufNoticeBuilder*) setContent:(NSString*) value;
- (MessageBufNoticeBuilder*) clearContent;

- (BOOL) hasServerTime;
- (SInt64) serverTime;
- (MessageBufNoticeBuilder*) setServerTime:(SInt64) value;
- (MessageBufNoticeBuilder*) clearServerTime;
@end

#define User_userId @"userId"
#define User_token @"token"
#define User_appId @"appId"
#define User_loginType @"loginType"
#define User_deviceType @"deviceType"
#define User_deviceId @"deviceId"
#define User_version @"version"
@interface MessageBufUser : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasVersion_:1;
  BOOL hasLoginType_:1;
  BOOL hasToken_:1;
  BOOL hasAppId_:1;
  BOOL hasDeviceType_:1;
  BOOL hasDeviceId_:1;
  SInt64 userId;
  SInt64 version;
  SInt32 loginType;
  NSString* token;
  NSString* appId;
  NSString* deviceType;
  NSString* deviceId;
}
- (BOOL) hasUserId;
- (BOOL) hasToken;
- (BOOL) hasAppId;
- (BOOL) hasLoginType;
- (BOOL) hasDeviceType;
- (BOOL) hasDeviceId;
- (BOOL) hasVersion;
@property (readonly) SInt64 userId;
@property (readonly, strong) NSString* token;
@property (readonly, strong) NSString* appId;
@property (readonly) SInt32 loginType;
@property (readonly, strong) NSString* deviceType;
@property (readonly, strong) NSString* deviceId;
@property (readonly) SInt64 version;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageBufUserBuilder*) builder;
+ (MessageBufUserBuilder*) builder;
+ (MessageBufUserBuilder*) builderWithPrototype:(MessageBufUser*) prototype;
- (MessageBufUserBuilder*) toBuilder;

+ (MessageBufUser*) parseFromData:(NSData*) data;
+ (MessageBufUser*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufUser*) parseFromInputStream:(NSInputStream*) input;
+ (MessageBufUser*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufUser*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageBufUser*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageBufUserBuilder : PBGeneratedMessageBuilder {
@private
  MessageBufUser* resultUser;
}

- (MessageBufUser*) defaultInstance;

- (MessageBufUserBuilder*) clear;
- (MessageBufUserBuilder*) clone;

- (MessageBufUser*) build;
- (MessageBufUser*) buildPartial;

- (MessageBufUserBuilder*) mergeFrom:(MessageBufUser*) other;
- (MessageBufUserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageBufUserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (SInt64) userId;
- (MessageBufUserBuilder*) setUserId:(SInt64) value;
- (MessageBufUserBuilder*) clearUserId;

- (BOOL) hasToken;
- (NSString*) token;
- (MessageBufUserBuilder*) setToken:(NSString*) value;
- (MessageBufUserBuilder*) clearToken;

- (BOOL) hasAppId;
- (NSString*) appId;
- (MessageBufUserBuilder*) setAppId:(NSString*) value;
- (MessageBufUserBuilder*) clearAppId;

- (BOOL) hasLoginType;
- (SInt32) loginType;
- (MessageBufUserBuilder*) setLoginType:(SInt32) value;
- (MessageBufUserBuilder*) clearLoginType;

- (BOOL) hasDeviceType;
- (NSString*) deviceType;
- (MessageBufUserBuilder*) setDeviceType:(NSString*) value;
- (MessageBufUserBuilder*) clearDeviceType;

- (BOOL) hasDeviceId;
- (NSString*) deviceId;
- (MessageBufUserBuilder*) setDeviceId:(NSString*) value;
- (MessageBufUserBuilder*) clearDeviceId;

- (BOOL) hasVersion;
- (SInt64) version;
- (MessageBufUserBuilder*) setVersion:(SInt64) value;
- (MessageBufUserBuilder*) clearVersion;
@end

#define KeepAlive_ping @"ping"
@interface MessageBufKeepAlive : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPing_:1;
  NSString* ping;
}
- (BOOL) hasPing;
@property (readonly, strong) NSString* ping;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageBufKeepAliveBuilder*) builder;
+ (MessageBufKeepAliveBuilder*) builder;
+ (MessageBufKeepAliveBuilder*) builderWithPrototype:(MessageBufKeepAlive*) prototype;
- (MessageBufKeepAliveBuilder*) toBuilder;

+ (MessageBufKeepAlive*) parseFromData:(NSData*) data;
+ (MessageBufKeepAlive*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufKeepAlive*) parseFromInputStream:(NSInputStream*) input;
+ (MessageBufKeepAlive*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufKeepAlive*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageBufKeepAlive*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageBufKeepAliveBuilder : PBGeneratedMessageBuilder {
@private
  MessageBufKeepAlive* resultKeepAlive;
}

- (MessageBufKeepAlive*) defaultInstance;

- (MessageBufKeepAliveBuilder*) clear;
- (MessageBufKeepAliveBuilder*) clone;

- (MessageBufKeepAlive*) build;
- (MessageBufKeepAlive*) buildPartial;

- (MessageBufKeepAliveBuilder*) mergeFrom:(MessageBufKeepAlive*) other;
- (MessageBufKeepAliveBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageBufKeepAliveBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPing;
- (NSString*) ping;
- (MessageBufKeepAliveBuilder*) setPing:(NSString*) value;
- (MessageBufKeepAliveBuilder*) clearPing;
@end

#define KeepAliveReceipt_pong @"pong"
@interface MessageBufKeepAliveReceipt : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPong_:1;
  NSString* pong;
}
- (BOOL) hasPong;
@property (readonly, strong) NSString* pong;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageBufKeepAliveReceiptBuilder*) builder;
+ (MessageBufKeepAliveReceiptBuilder*) builder;
+ (MessageBufKeepAliveReceiptBuilder*) builderWithPrototype:(MessageBufKeepAliveReceipt*) prototype;
- (MessageBufKeepAliveReceiptBuilder*) toBuilder;

+ (MessageBufKeepAliveReceipt*) parseFromData:(NSData*) data;
+ (MessageBufKeepAliveReceipt*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufKeepAliveReceipt*) parseFromInputStream:(NSInputStream*) input;
+ (MessageBufKeepAliveReceipt*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufKeepAliveReceipt*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageBufKeepAliveReceipt*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageBufKeepAliveReceiptBuilder : PBGeneratedMessageBuilder {
@private
  MessageBufKeepAliveReceipt* resultKeepAliveReceipt;
}

- (MessageBufKeepAliveReceipt*) defaultInstance;

- (MessageBufKeepAliveReceiptBuilder*) clear;
- (MessageBufKeepAliveReceiptBuilder*) clone;

- (MessageBufKeepAliveReceipt*) build;
- (MessageBufKeepAliveReceipt*) buildPartial;

- (MessageBufKeepAliveReceiptBuilder*) mergeFrom:(MessageBufKeepAliveReceipt*) other;
- (MessageBufKeepAliveReceiptBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageBufKeepAliveReceiptBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPong;
- (NSString*) pong;
- (MessageBufKeepAliveReceiptBuilder*) setPong:(NSString*) value;
- (MessageBufKeepAliveReceiptBuilder*) clearPong;
@end

#define Receipt_type @"type"
#define Receipt_stateCode @"stateCode"
#define Receipt_messageACK @"messageAck"
#define Receipt_loginACK @"loginAck"
@interface MessageBufReceipt : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasType_:1;
  BOOL hasStateCode_:1;
  BOOL hasMessageAck_:1;
  BOOL hasLoginAck_:1;
  SInt32 type;
  SInt32 stateCode;
  MessageBufMessageACK* messageAck;
  MessageBufLoginACK* loginAck;
}
- (BOOL) hasType;
- (BOOL) hasStateCode;
- (BOOL) hasMessageAck;
- (BOOL) hasLoginAck;
@property (readonly) SInt32 type;
@property (readonly) SInt32 stateCode;
@property (readonly, strong) MessageBufMessageACK* messageAck;
@property (readonly, strong) MessageBufLoginACK* loginAck;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageBufReceiptBuilder*) builder;
+ (MessageBufReceiptBuilder*) builder;
+ (MessageBufReceiptBuilder*) builderWithPrototype:(MessageBufReceipt*) prototype;
- (MessageBufReceiptBuilder*) toBuilder;

+ (MessageBufReceipt*) parseFromData:(NSData*) data;
+ (MessageBufReceipt*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufReceipt*) parseFromInputStream:(NSInputStream*) input;
+ (MessageBufReceipt*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufReceipt*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageBufReceipt*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageBufReceiptBuilder : PBGeneratedMessageBuilder {
@private
  MessageBufReceipt* resultReceipt;
}

- (MessageBufReceipt*) defaultInstance;

- (MessageBufReceiptBuilder*) clear;
- (MessageBufReceiptBuilder*) clone;

- (MessageBufReceipt*) build;
- (MessageBufReceipt*) buildPartial;

- (MessageBufReceiptBuilder*) mergeFrom:(MessageBufReceipt*) other;
- (MessageBufReceiptBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageBufReceiptBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (SInt32) type;
- (MessageBufReceiptBuilder*) setType:(SInt32) value;
- (MessageBufReceiptBuilder*) clearType;

- (BOOL) hasStateCode;
- (SInt32) stateCode;
- (MessageBufReceiptBuilder*) setStateCode:(SInt32) value;
- (MessageBufReceiptBuilder*) clearStateCode;

- (BOOL) hasMessageAck;
- (MessageBufMessageACK*) messageAck;
- (MessageBufReceiptBuilder*) setMessageAck:(MessageBufMessageACK*) value;
- (MessageBufReceiptBuilder*) setMessageAckBuilder:(MessageBufMessageACKBuilder*) builderForValue;
- (MessageBufReceiptBuilder*) mergeMessageAck:(MessageBufMessageACK*) value;
- (MessageBufReceiptBuilder*) clearMessageAck;

- (BOOL) hasLoginAck;
- (MessageBufLoginACK*) loginAck;
- (MessageBufReceiptBuilder*) setLoginAck:(MessageBufLoginACK*) value;
- (MessageBufReceiptBuilder*) setLoginAckBuilder:(MessageBufLoginACKBuilder*) builderForValue;
- (MessageBufReceiptBuilder*) mergeLoginAck:(MessageBufLoginACK*) value;
- (MessageBufReceiptBuilder*) clearLoginAck;
@end

#define MessageACK_sessId @"sessId"
#define MessageACK_sessVer @"sessVer"
#define MessageACK_msgId @"msgId"
#define MessageACK_msgVer @"msgVer"
#define MessageACK_cMsgId @"cMsgId"
#define MessageACK_serverTime @"serverTime"
@interface MessageBufMessageACK : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSessId_:1;
  BOOL hasSessVer_:1;
  BOOL hasMsgId_:1;
  BOOL hasMsgVer_:1;
  BOOL hasCMsgId_:1;
  BOOL hasServerTime_:1;
  SInt64 sessId;
  SInt64 sessVer;
  SInt64 msgId;
  SInt64 msgVer;
  SInt64 cMsgId;
  SInt64 serverTime;
}
- (BOOL) hasSessId;
- (BOOL) hasSessVer;
- (BOOL) hasMsgId;
- (BOOL) hasMsgVer;
- (BOOL) hasCMsgId;
- (BOOL) hasServerTime;
@property (readonly) SInt64 sessId;
@property (readonly) SInt64 sessVer;
@property (readonly) SInt64 msgId;
@property (readonly) SInt64 msgVer;
@property (readonly) SInt64 cMsgId;
@property (readonly) SInt64 serverTime;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageBufMessageACKBuilder*) builder;
+ (MessageBufMessageACKBuilder*) builder;
+ (MessageBufMessageACKBuilder*) builderWithPrototype:(MessageBufMessageACK*) prototype;
- (MessageBufMessageACKBuilder*) toBuilder;

+ (MessageBufMessageACK*) parseFromData:(NSData*) data;
+ (MessageBufMessageACK*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufMessageACK*) parseFromInputStream:(NSInputStream*) input;
+ (MessageBufMessageACK*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufMessageACK*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageBufMessageACK*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageBufMessageACKBuilder : PBGeneratedMessageBuilder {
@private
  MessageBufMessageACK* resultMessageAck;
}

- (MessageBufMessageACK*) defaultInstance;

- (MessageBufMessageACKBuilder*) clear;
- (MessageBufMessageACKBuilder*) clone;

- (MessageBufMessageACK*) build;
- (MessageBufMessageACK*) buildPartial;

- (MessageBufMessageACKBuilder*) mergeFrom:(MessageBufMessageACK*) other;
- (MessageBufMessageACKBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageBufMessageACKBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSessId;
- (SInt64) sessId;
- (MessageBufMessageACKBuilder*) setSessId:(SInt64) value;
- (MessageBufMessageACKBuilder*) clearSessId;

- (BOOL) hasSessVer;
- (SInt64) sessVer;
- (MessageBufMessageACKBuilder*) setSessVer:(SInt64) value;
- (MessageBufMessageACKBuilder*) clearSessVer;

- (BOOL) hasMsgId;
- (SInt64) msgId;
- (MessageBufMessageACKBuilder*) setMsgId:(SInt64) value;
- (MessageBufMessageACKBuilder*) clearMsgId;

- (BOOL) hasMsgVer;
- (SInt64) msgVer;
- (MessageBufMessageACKBuilder*) setMsgVer:(SInt64) value;
- (MessageBufMessageACKBuilder*) clearMsgVer;

- (BOOL) hasCMsgId;
- (SInt64) cMsgId;
- (MessageBufMessageACKBuilder*) setCMsgId:(SInt64) value;
- (MessageBufMessageACKBuilder*) clearCMsgId;

- (BOOL) hasServerTime;
- (SInt64) serverTime;
- (MessageBufMessageACKBuilder*) setServerTime:(SInt64) value;
- (MessageBufMessageACKBuilder*) clearServerTime;
@end

#define LoginACK_sessVer @"sessVer"
@interface MessageBufLoginACK : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSessVer_:1;
  SInt64 sessVer;
}
- (BOOL) hasSessVer;
@property (readonly) SInt64 sessVer;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageBufLoginACKBuilder*) builder;
+ (MessageBufLoginACKBuilder*) builder;
+ (MessageBufLoginACKBuilder*) builderWithPrototype:(MessageBufLoginACK*) prototype;
- (MessageBufLoginACKBuilder*) toBuilder;

+ (MessageBufLoginACK*) parseFromData:(NSData*) data;
+ (MessageBufLoginACK*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufLoginACK*) parseFromInputStream:(NSInputStream*) input;
+ (MessageBufLoginACK*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageBufLoginACK*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageBufLoginACK*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageBufLoginACKBuilder : PBGeneratedMessageBuilder {
@private
  MessageBufLoginACK* resultLoginAck;
}

- (MessageBufLoginACK*) defaultInstance;

- (MessageBufLoginACKBuilder*) clear;
- (MessageBufLoginACKBuilder*) clone;

- (MessageBufLoginACK*) build;
- (MessageBufLoginACK*) buildPartial;

- (MessageBufLoginACKBuilder*) mergeFrom:(MessageBufLoginACK*) other;
- (MessageBufLoginACKBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageBufLoginACKBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSessVer;
- (SInt64) sessVer;
- (MessageBufLoginACKBuilder*) setSessVer:(SInt64) value;
- (MessageBufLoginACKBuilder*) clearSessVer;
@end

@interface MessageBufBuilder : PBGeneratedMessageBuilder {
@private
  MessageBuf* resultMessageBuf;
}

- (MessageBuf*) defaultInstance;

- (MessageBufBuilder*) clear;
- (MessageBufBuilder*) clone;

- (MessageBuf*) build;
- (MessageBuf*) buildPartial;

- (MessageBufBuilder*) mergeFrom:(MessageBuf*) other;
- (MessageBufBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageBufBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIsRequest;
- (BOOL) isRequest;
- (MessageBufBuilder*) setIsRequest:(BOOL) value;
- (MessageBufBuilder*) clearIsRequest;

- (BOOL) hasRequestType;
- (MessageBufRequestTypeEnum) requestType;
- (MessageBufBuilder*) setRequestType:(MessageBufRequestTypeEnum) value;
- (MessageBufBuilder*) clearRequestType;

- (BOOL) hasMessage;
- (MessageBufMessage*) message;
- (MessageBufBuilder*) setMessage:(MessageBufMessage*) value;
- (MessageBufBuilder*) setMessageBuilder:(MessageBufMessageBuilder*) builderForValue;
- (MessageBufBuilder*) mergeMessage:(MessageBufMessage*) value;
- (MessageBufBuilder*) clearMessage;

- (BOOL) hasSession;
- (MessageBufSession*) session;
- (MessageBufBuilder*) setSession:(MessageBufSession*) value;
- (MessageBufBuilder*) setSessionBuilder:(MessageBufSessionBuilder*) builderForValue;
- (MessageBufBuilder*) mergeSession:(MessageBufSession*) value;
- (MessageBufBuilder*) clearSession;

- (BOOL) hasNotice;
- (MessageBufNotice*) notice;
- (MessageBufBuilder*) setNotice:(MessageBufNotice*) value;
- (MessageBufBuilder*) setNoticeBuilder:(MessageBufNoticeBuilder*) builderForValue;
- (MessageBufBuilder*) mergeNotice:(MessageBufNotice*) value;
- (MessageBufBuilder*) clearNotice;

- (BOOL) hasKeepAlive;
- (MessageBufKeepAlive*) keepAlive;
- (MessageBufBuilder*) setKeepAlive:(MessageBufKeepAlive*) value;
- (MessageBufBuilder*) setKeepAliveBuilder:(MessageBufKeepAliveBuilder*) builderForValue;
- (MessageBufBuilder*) mergeKeepAlive:(MessageBufKeepAlive*) value;
- (MessageBufBuilder*) clearKeepAlive;

- (BOOL) hasUser;
- (MessageBufUser*) user;
- (MessageBufBuilder*) setUser:(MessageBufUser*) value;
- (MessageBufBuilder*) setUserBuilder:(MessageBufUserBuilder*) builderForValue;
- (MessageBufBuilder*) mergeUser:(MessageBufUser*) value;
- (MessageBufBuilder*) clearUser;

- (BOOL) hasReceipt;
- (MessageBufReceipt*) receipt;
- (MessageBufBuilder*) setReceipt:(MessageBufReceipt*) value;
- (MessageBufBuilder*) setReceiptBuilder:(MessageBufReceiptBuilder*) builderForValue;
- (MessageBufBuilder*) mergeReceipt:(MessageBufReceipt*) value;
- (MessageBufBuilder*) clearReceipt;

- (BOOL) hasKeepAliveReceipt;
- (MessageBufKeepAliveReceipt*) keepAliveReceipt;
- (MessageBufBuilder*) setKeepAliveReceipt:(MessageBufKeepAliveReceipt*) value;
- (MessageBufBuilder*) setKeepAliveReceiptBuilder:(MessageBufKeepAliveReceiptBuilder*) builderForValue;
- (MessageBufBuilder*) mergeKeepAliveReceipt:(MessageBufKeepAliveReceipt*) value;
- (MessageBufBuilder*) clearKeepAliveReceipt;
@end


// @@protoc_insertion_point(global_scope)
